Settings:
  Commands:
    CityBuildV2:
      Name: 'citybuildv2'
      Aliases: ['cbv2']
    Signeidt:
      Name: 'signedit'
      Aliases: ['schild']
      Active: true
    ClearChat:
      Name: 'clearchat'
      Aliases: ['cc', 'chatclear']
      Active: true
    Status:
      Name: 'status'
      Aliases: []
      Active: true
    Food:
      Name: 'food'
      Aliases: []
      Active: true
    Teleport:
      Name: 'teleport'
      Aliases: ['tp']
      Active: true
    StartKick:
      Name: 'startkick'
      Aliases: ['votekick']
      Active: true
    Unstartkick:
      Name: 'unstartkick'
      Aliases: ['unvotekick']
      Active: true
    YesCommand:
      Name: 'yes'
      Aliases: ['ja']
      Active: true
    NoCommand:
      Name: 'no'
      Aliases: ['nein']
      Active: true
    SlowChat:
      Name: 'slowchat'
      Aliases: ['chatslow']
      Active: true
    Head:
      Name: 'head'
      Aliases: ['kopf', 'skull']
      Active: true
    Breakblock:
      Name: 'breakblock'
      Aliases: ['bb']
      Active: true
    CommandSpy:
      Name: 'commandspy'
      Aliases: ['cspy']
      Active: true
    AllOrNothing:
      Name: 'allornothing'
      Aliases: ['allesodernichts', 'aon']
      Active: true
    MuteP:
      Name: 'mutep'
      Aliases: ['muteplayer']
      Active: true
    UnmuteP:
      Name: 'unmutep'
      Aliases: ['unmuteplayer']
      Active: true
    TpHere:
      Name: 'tphere'
      Aliases: ['tph']
      Active: true
    Glow:
      Name: 'glow'
      Aliases: ['light']
      Active: true