Settings:
  Commands:
    Schild: true
    ClearChat: true
    Sign: true
    Unsign: true
    Status: true
    Food: true
    Teleport: true
    StartKick: true
    Unstartkick: true
    YesCommand: true
    NoCommand: true
    SlowChat: true