Settings:
  Commands:
    CityBuildV2:
      Name: 'citybuildv2'
      Aliases: [ 'cbv2' ]
    Signedit:
      Name: 'signedit'
      Aliases: [ 'schild' ]
      Active: true
    ClearChat:
      Name: 'clearchat'
      Aliases: [ 'cc', 'chatclear' ]
      Active: true
    Status:
      Name: 'status'
      Aliases: [ ]
      Active: true
    Food:
      Name: 'food'
      Aliases: [ ]
      Active: true
    Teleport:
      Name: 'teleport'
      Aliases: [ 'tp' ]
      Active: true
    StartKick:
      Name: 'startkick'
      Aliases: [ 'votekick' ]
      Active: true
    Unstartkick:
      Name: 'unstartkick'
      Aliases: [ 'unvotekick' ]
      Active: true
    YesCommand:
      Name: 'yes'
      Aliases: [ 'ja' ]
      Active: true
    NoCommand:
      Name: 'no'
      Aliases: [ 'nein' ]
      Active: true
    SlowChat:
      Name: 'slowchat'
      Aliases: [ 'chatslow' ]
      Active: true
    Head:
      Name: 'head'
      Aliases: [ 'kopf', 'skull' ]
      Active: true
    Breakblock:
      Name: 'breakblock'
      Aliases: [ 'bb' ]
      Active: true
    CommandSpy:
      Name: 'commandspy'
      Aliases: [ 'cspy' ]
      Active: true
    AllOrNothing:
      Name: 'allornothing'
      Aliases: [ 'allesodernichts', 'aon' ]
      Active: true
    MuteP:
      Name: 'mutep'
      Aliases: [ 'muteplayer' ]
      Active: true
    UnmuteP:
      Name: 'unmutep'
      Aliases: [ 'unmuteplayer' ]
      Active: true
    TpHere:
      Name: 'tphere'
      Aliases: [ 'tph' ]
      Active: true
    Glow:
      Name: 'glow'
      Aliases: [ 'light' ]
      Active: true
    GameMode:
      Name: 'gamemode'
      Aliases: [ 'gm' ]
      Active: true
    Spawn:
      Name: 'Spawn'
      Aliases: [ ]
      Active: true
    GiftRank:
      Name: 'giftrank'
      Aliases: [ 'premium', 'gold' ]
      Active: true
    CheckPlot:
      Name: 'checkplot'
      Aliases: [ ]
      Active: true
    Sudo:
      Name: 'sudo'
      Aliases: [ 'perform' ]
      Active: true
    Clear:
      Name: 'clear'
      Aliases: [ 'ci', 'clearinventory' ]
      Active: true
    Fly:
      Name: 'fly'
      Aliases: [ 'flymode' ]
      Active: true
    Feed:
      Name: 'feed'
      Aliases: [ 'essen' ]
      Active: true
    Heal:
      Name: 'heal'
      Aliases: [ 'leben' ]
      Active: true
    Farmworld:
      Name: 'farmworld'
      Aliases: [ 'farmwelt', 'farm' ]
      Active: true
    Nether:
      Name: 'nether'
      Aliases: [ '' ]
      Active: true
    Invsee:
      Name: 'invsee'
      Aliases: [ 'inventar' ]
      Active: true
    God:
      Name: 'god'
      Aliases: [ 'invulnerable' ]
      Active: true
    Speed:
      Name: 'speed'
      Aliases: [ 'speeding' ]
      Active: true