name: CityBuildV2
version: 2.2.1-RELEASE
authors:
  - Justin_SGD
  - KeinByte
  - Forumat
main: de.crashmash.citybuild.CityBuildV2
softdepend:
  - PlotSquared
  - AutoUpdaterAPI
  - DeveloperAPI
api-version: 1.13