name: CityBuildV2
version: 1.0.0-BETA
authors:
  - Justin_SGD
  - KeinByte
main: de.crashmash.citybuild.CityBuildV2
commands:
  schild:
    description: 'Verändere den Text auf Schilder.'
  clearchat:
    description: 'Cleared den Ingame Chat.'
  status:
    description: 'Sende eine Nachricht beim joinen.'
  food:
    description: 'Setze ein Essensschwein.'
  tp:
    description: 'Teleportiere dich zu einer Location oder zu anderen Spielern.'
  ja:
    description: 'Stimme gegen einen Spieler bei einer Abstimmung.'
    aliases:
      - yes
  nein:
    description: 'Stimme für einen Spieler bei einer Abstimmung.'
    aliases:
      - no