name: CityBuildV2
version: $VERSION
authors:
  - JuByte
  - Justin_SGD
  - KeinByte
  - Forumat
main: com.jubyte.citybuild.CityBuildV2
softdepend:
  - PlotSquared
  - AutoUpdaterAPI
  - DeveloperAPI
  - JuByteLibraries
  - ProtocolLib
api-version: 1.13