name: CityBuildV2
version: 1.0.0-BETA
authors:
  - Justin_SGD
  - KeinByte
main: de.crashmash.citybuild.CityBuildV2
commands:
  schild:
    description: 'Verändere den Text auf Schilder.'
  clearchat:
    description: 'Cleared den Ingame Chat.'
  status:
    description: 'Sende eine Nachricht beim joinen.'