name: CityBuildV2
version: 2.11.0-RELEASE
authors:
  - Justin_SGD
  - KeinByte
  - Forumat
main: de.jubyte.citybuild.CityBuildV2
softdepend:
  - PlotSquared
  - AutoUpdaterAPI
  - DeveloperAPI
  - DKBans
  - McNative
  - ProtocolLib
api-version: 1.13